package databaseapp;


import databaseapp.student;
import static java.lang.Integer.parseInt;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
public class DataForm extends javax.swing.JFrame  {

    //student stud;
      DatabaseApp dataapp=new DatabaseApp();
      
      //dataapp.stud=stud;
     
      student stud=dataapp.stud;
      //student stud=new student();
    
      public DataForm() throws Exception {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        name = new javax.swing.JLabel();
        namebox = new javax.swing.JTextField();
        age = new javax.swing.JLabel();
        agebox = new javax.swing.JTextField();
        next = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        name.setForeground(new java.awt.Color(255, 255, 0));
        name.setText("Name");
        getContentPane().add(name);
        name.setBounds(58, 59, 50, 30);

        namebox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameboxActionPerformed(evt);
            }
        });
        getContentPane().add(namebox);
        namebox.setBounds(126, 64, 170, 30);

        age.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        age.setForeground(new java.awt.Color(255, 255, 0));
        age.setText("Age");
        getContentPane().add(age);
        age.setBounds(70, 121, 30, 20);

        agebox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageboxActionPerformed(evt);
            }
        });
        getContentPane().add(agebox);
        agebox.setBounds(126, 118, 170, 30);

        next.setBackground(new java.awt.Color(0, 255, 255));
        next.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        next.setText("next");
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });
        getContentPane().add(next);
        next.setBounds(140, 230, 80, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\interface.jpg")); // NOI18N
        jLabel1.setText("icon");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 660, 320);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameboxActionPerformed
       
        //System.out.println(name);
        
    }//GEN-LAST:event_nameboxActionPerformed

    private void ageboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageboxActionPerformed
       
       //System.out.println(age);
        
    }//GEN-LAST:event_ageboxActionPerformed

    
    
    
    private void nextActionPerformed(java.awt.event.ActionEvent evt)  {

     
         String name=namebox.getText();
          int age=parseInt(agebox.getText());
          
          
          System.out.println("bitch");
        stud.setName(name);
         stud.setAge(age);
         
         System.out.println(stud.getName());
         System.out.println(stud.getAge());
         
         //stud.getAge();
          
          // stud=new student("chamath",23);
          
          
           this.setVisible(false);
           
           System.out.println("wake up");
          try {
              dataapp.database_part();
          } catch (Exception ex) {
              Logger.getLogger(DataForm.class.getName()).log(Level.SEVERE, null, ex);
          }
          
        
         
         
    }                                    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new DataForm().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(DataForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel age;
    private javax.swing.JTextField agebox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel name;
    private javax.swing.JTextField namebox;
    private javax.swing.JButton next;
    // End of variables declaration//GEN-END:variables
}
